const slideImg=document.getElementById('slide');const prevBtn=document.getElementById('prevBtn');const nextBtn=document.getElementById('nextBtn');const possiblePatterns=[(n)=>`images/pic${n}.jpg`,(n)=>`images/pic${n}.jpeg`,(n)=>`images/${n}.jpg`,(n)=>`images/img${n}.jpg`,(n)=>`images/photo${n}.jpg`,(n)=>`images/${n}.png`,(n)=>`images/pic${n}.png`,(n)=>`images/${n}.webp`];let imgs=[];let idx=0;function getEgyptTime(){const now=new Date();const utc=now.getTime()+(now.getTimezoneOffset()*60000);const egyptOffset=2*60*60000;return new Date(utc+egyptOffset)}
const startDate=new Date("2024-11-29T00:00:00");function updateCountdown(){const now=getEgyptTime();let diff=now-startDate;if(diff<0)diff=0;const totalDays=Math.floor(diff/(1000*60*60*24));const years=Math.floor(totalDays/365);const remainingDaysAfterYears=totalDays%365;const months=Math.floor(remainingDaysAfterYears/30);const days=remainingDaysAfterYears%30;const hours=Math.floor(diff/(1000*60*60))%24;const minutes=Math.floor(diff/(1000*60))%60;const seconds=Math.floor(diff/1000)%60;let text="";if(years>0)text+=`<span>${years} سنة،</span> `;text+=`<span>${months} شهر،</span> <span>${days} يوم،</span> <span>${hours} ساعة،</span> <span>${minutes} دقيقة،</span> <span>${seconds} ثانية</span>`;document.getElementById("countdown").innerHTML=text}
setInterval(updateCountdown,1000);updateCountdown();function testImage(url){return new Promise((res)=>{const i=new Image();i.onload=()=>res(!0);i.onerror=()=>res(!1);i.src=url})}
async function autoDiscoverImages(){const maxTry=30;for(let n=1;n<=maxTry;n++){for(const p of possiblePatterns){const url=p(n);const ok=await testImage(url);if(ok&&!imgs.includes(url))imgs.push(url);}}
if(imgs.length===0){imgs=["images/placeholder.jpg"]}
slideImg.style.opacity=0;setTimeout(()=>{slideImg.src=imgs[0];slideImg.style.opacity=1},200)}
autoDiscoverImages();function showIndex(i){idx=(i+imgs.length)%imgs.length;slideImg.style.opacity=0;setTimeout(()=>{slideImg.src=imgs[idx];slideImg.style.opacity=1},220)}
function nextSlide(){showIndex(idx+1)}
function prevSlide(){showIndex(idx-1)}
nextBtn.addEventListener('click',nextSlide);prevBtn.addEventListener('click',prevSlide);let autoTimer=setInterval(nextSlide,4000);document.querySelector('.slide-frame').addEventListener('mouseenter',()=>clearInterval(autoTimer));document.querySelector('.slide-frame').addEventListener('mouseleave',()=>{clearInterval(autoTimer);autoTimer=setInterval(nextSlide,4000)});function updateTimer(){const start=new Date("2023-11-29T00:00:00");const now=new Date();const diff=now-start;const days=Math.floor(diff/(1000*60*60*24));const hours=Math.floor((diff/(1000*60*60))%24);const mins=Math.floor((diff/(1000*60))%60);const secs=Math.floor((diff/1000)%60);const el=document.getElementById('time');if(el)el.textContent=`${days} Days ${hours} Hours ${mins} Minutes ${secs} Seconds`}
setInterval(updateTimer,1000);updateTimer();const bgm=document.getElementById('bgm');function ensureAudioPlay(){if(bgm&&bgm.paused){const playPromise=bgm.play();if(playPromise!==undefined){playPromise.catch(()=>{const resume=()=>{bgm.play().catch(()=>{});window.removeEventListener('click',resume)};window.addEventListener('click',resume)})}}}
ensureAudioPlay()
